//! Agent Chat — adapter abstraction (Contract C2).
//!
//! Each agent kind implements [`AgentAdapter`] + [`AgentSession`]; the bridge
//! pumps events from a session into the IPC/SSE transport. New agents = new
//! adapter only; the protocol and page are untouched (OCP).

use async_trait::async_trait;
use tokio::sync::mpsc;

use crate::agent::chat::events::{SessionRequest, StreamEvent};
use crate::common::agent::types::{AgentConfig, ChatStart};
pub mod acp;
pub mod deepseek;
pub mod serve;

pub use acp::AcpAdapter;
pub use deepseek::DeepSeekHarnessAdapter;
pub use serve::ServeAdapter;

use crate::common::error::AppError;

/// Identifies an agent kind. `custom` covers user-defined commands.
/// 会话持久化用（ResumeCursor.agent_kind）。
#[derive(Clone, Debug, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum AgentKind {
    /// opencode agent.
    Opencode,
    /// claude-code agent.
    ClaudeCode,
    /// gemini agent.
    Gemini,
    /// codex agent.
    Codex,
    /// qoder agent.
    Qoder,
    /// codebuddy agent.
    Codebuddy,
    /// User-defined custom agent（含 mockAgent 等未枚举 id）。
    Custom,
}

impl AgentKind {
    /// Map an agent id (as registered in `AgentManager`) to a kind.
    #[must_use]
    pub fn from_agent_id(agent_id: &str) -> Self {
        match agent_id {
            "opencode" => Self::Opencode,
            "claude-code" => Self::ClaudeCode,
            "gemini" => Self::Gemini,
            "codex" => Self::Codex,
            "qoder" => Self::Qoder,
            "codebuddy" => Self::Codebuddy,
            _ => Self::Custom,
        }
    }
}

/// Build the adapter for an agent from its `AgentConfig`。
///
/// 分派依据 `config.chat`（CHAT 能力数据，自包含启动方式，零 id 特判）：
/// - `None` → 该 agent 无 CHAT 能力（返回 `Unsupported`）；
/// - `Mock` → [`AcpAdapter::mock`]（进程内，无子进程）；
/// - `Acp { args }` → [`AcpAdapter`]（`command + args` 启动，opencode 的
///   `["opencode","acp"]` 由内置定义提供）；
/// - `Serve` → [`ServeAdapter`]（opencode serve 的 REST + SSE 传输）；
/// - `Jsonl` → [`DeepSeekHarnessAdapter`]（stdio JSON-Lines）。
pub fn adapter_for(config: &AgentConfig) -> Result<Box<dyn AgentAdapter>, AppError> {
    match &config.chat {
        None => Err(AppError::Unsupported(format!(
            "agent '{}' 无 CHAT 能力（仅终端/Headless 形态）",
            config.id
        ))),
        Some(ChatStart::Mock) => Ok(Box::new(AcpAdapter::mock())),
        Some(ChatStart::Acp { args }) => {
            let mut cmd = config.cmd_vec();
            cmd.extend(args.iter().cloned());
            Ok(Box::new(AcpAdapter::new(cmd)))
        }
        Some(ChatStart::Serve) => Ok(Box::new(ServeAdapter::new())),
        Some(ChatStart::Jsonl) => Ok(Box::new(DeepSeekHarnessAdapter::new(config.cmd_vec()))),
    }
}

/// Binds a session to its working context (A4 — protocolised G4).
#[derive(Clone, Debug)]
pub struct AgentContext {
    /// Agent identifier（真实 id，来自 AgentManager；adapter 用于 SessionStart.agent）。
    pub agent_id: String,
    /// Opaque session identifier (generated by the command layer; must match
    /// the id used in events and the session registry).
    pub session_id: String,
    /// Project identifier.
    pub project_id: String,
    /// Human-readable project name.
    pub project_name: String,
    /// Execution environment: `local` | `wsl` | `ssh`.
    pub env: String,
    /// Skill IDs enabled for this session.
    pub skills: Vec<String>,
    /// File paths attached as context.
    pub files: Vec<String>,
    /// Approval mode: `auto` | `confirm`.
    pub mode: String,
    /// The user's prompt for this turn.
    pub prompt: String,
    /// Model ID selected by the user (per-session / per-turn). `None` → agent default.
    pub model_id: Option<String>,
}

/// How an agent session is obtained (IO shape axis, A1/A5). The trait stays
/// transport-agnostic; each adapter picks Spawn / Connect / Serve internally.
#[async_trait]
pub trait AgentAdapter: Send + Sync {
    /// Returns the agent kind this adapter handles.
    fn kind(&self) -> AgentKind;
    /// Create a session bound to `ctx`. Spawns or connects internally.
    async fn create(&self, ctx: &AgentContext) -> Result<Box<dyn AgentSession>, AppError>;
    /// Resume an existing native session (from the agent's own persisted
    /// storage, e.g. opencode's SQLite or claude-code's JSONL) as a live chat.
    ///
    /// Default: unsupported. Adapters opt in by overriding this plus
    /// [`AgentAdapter::supports_chat_resume`] — new agents never force changes
    /// onto callers (OCP).
    async fn resume(
        &self,
        ctx: &AgentContext,
        native_session_id: &str,
    ) -> Result<Box<dyn AgentSession>, AppError> {
        let _ = ctx;
        Err(AppError::Agent(format!(
            "agent {:?} does not support chat resume (native session {native_session_id})",
            self.kind()
        )))
    }
    /// Whether this adapter can resume a native session as a live chat.
    /// Drives frontend entry visibility (Chat tab list / Histor panel action).
    fn supports_chat_resume(&self) -> bool {
        false
    }
}

/// A live, cancelable agent session (A5 — standard adapter shape).
#[async_trait]
pub trait AgentSession: Send {
    /// Pull the next event. `None` means the session ended.
    async fn next(&mut self) -> Option<Result<StreamEvent, AppError>>;
    /// Send a page→agent message (Gate return / input / rebind / cancel).
    async fn send(&mut self, req: SessionRequest) -> Result<(), AppError>;
    /// Stop the pump, then kill the underlying process after a grace period.
    async fn cancel(&mut self);
    /// Opaque resume handle for session restore.
    fn resume_id(&self) -> Option<String>;
    /// Cloneable page→agent request channel for manager routing.
    ///
    /// Adapters whose `send()` writes directly to the child should return
    /// `None`; channel-backed adapters return a clone so the session registry
    /// can route `agent_approve` / `agent_input` / `agent_stream_cancel`
    /// without racing the event pump.
    fn request_channel(&self) -> Option<mpsc::Sender<SessionRequest>> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> AgentContext {
        AgentContext {
            agent_id: "opencode".into(),
            session_id: "ac_test".into(),
            project_id: "/tmp/demo".into(),
            project_name: "demo".into(),
            env: "local".into(),
            skills: vec![],
            files: vec![],
            mode: "auto".into(),
            prompt: String::new(),
            model_id: None,
        }
    }

    /// 未覆写 resume 的 adapter（AcpAdapter::mock）必须优雅拒绝而非 panic，
    /// 且 supports_chat_resume 默认关闭 —— 驱动前端入口显隐。
    #[tokio::test]
    async fn default_resume_is_unsupported_and_opt_in() {
        let adapter = AcpAdapter::mock();
        assert!(!adapter.supports_chat_resume());
        let msg = match adapter.resume(&ctx(), "ses_native_1").await {
            Err(e) => format!("{e:?}"),
            Ok(_) => panic!("default resume must return Err, not a session"),
        };
        assert!(
            msg.contains("does not support chat resume"),
            "error should explain resume unsupported: {msg}"
        );
    }
}
