// Re-export stub — migrated to src/features/terminal/components/terminalCache
export {
  createTerminalCacheBackend,
  terminalCache,
  terminalRebuildCallbacks,
  terminalWrapperRefs,
  executedAgentKeys,
  terminalCacheKey,
  log,
  destroyTerminalCache,
  destroyTerminalCachesByPrefix,
  refreshTerminal,
  wslTerminalCache,
  wslRebuildCallbacks,
  wslWrapperRefs,
  wslCacheKey,
  destroyWslCache,
  destroyWslCachesByPrefix,
  refreshWslTerminal,
  getWslSessionId,
  getWslOpenProjectIds,
  getAllWslOpenProjectIds,
  launchAgentInWslTerminal,
  switchAgentInWslTerminal,
  remoteTerminalCache,
  remoteRebuildCallbacks,
  remoteWrapperRefs,
  remoteCacheKey,
  destroyRemoteCache,
  destroyRemoteCachesByPrefix,
  refreshRemoteTerminal,
  launchAgentInRemoteTerminal,
  switchAgentInRemoteTerminal,
} from "@/features/terminal/components/terminalCache";
export type { CacheBackendOptions, WslTerminalCache, RemoteTerminalCache } from "@/features/terminal/components/terminalCache";
