use regex::Regex;

use crate::conversation::adapters::strip_ansi;

/// 标题字符上限（按 Unicode 标量，代理对安全）
pub(crate) const TITLE_MAX_CHARS: usize = 96;
/// 预览（摘要）字符上限
pub(crate) const PREVIEW_MAX_CHARS: usize = 220;

/// orca 对齐：省略号使用三连点 `...`（非单一 … 字符）
const ELLIPSIS: &str = "...";

/// 已知隐藏块标签对（大小写不敏感），整段移除 `<tag>...</tag>`
/// 来源：orca session-scanner-text-normalization.ts HIDDEN_TEXT_BLOCKS
const HIDDEN_BLOCKS: &[(&str, &str)] = &[
    ("system-reminder", "</system-reminder>"),
    ("codex_internal_context", "</codex_internal_context>"),
    ("goal_context", "</goal_context>"),
];

/// 抑制前缀：以注入指令开头 → 视为无语义（返回 None）
/// orca: '# AGENTS.md instructions' 与 '<INSTRUCTIONS>'
const AGENTS_INSTRUCTIONS_PREFIX: &str = "# agents.md instructions";
const XML_INSTRUCTIONS_PREFIX: &str = "<instructions>";

/// 应从文本开头剥离的句子级前缀（前缀之后的内容仍保留）。
/// 与 `HARNESS_INJECTED_PREFIXES` 重叠，但这里的语义是剥离前缀而非整条消息丢弃。
const HARNESS_SENTENCE_PREFIXES: &[&str] = &[
    "caveat: the messages below were generated by the user while running local commands",
    "this session is being continued from a previous conversation",
];

/// 预览消息环形缓冲上限（保留最近 N 条）
pub(crate) const PREVIEW_MESSAGE_LIMIT: usize = 5;

/// harness 注入的“伪用户消息”前缀（应排除出预览）。
/// 来源：orca harness-injected-user-turns.ts
const HARNESS_INJECTED_PREFIXES: &[&str] = &[
    "<task-notification>",
    "<system-reminder>",
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<bash-",
    "[request interrupted",
    "caveat: the messages below were generated by the user while running local commands",
    "this session is being continued from a previous conversation",
];

/// 规范化目标：标题或预览，决定截断长度。
#[derive(Clone, Copy)]
pub(crate) enum NormTarget {
    Title,
    Preview,
}

/// 对会话标题/预览文本施加确定性净化流水线（去噪而非摘要）。
///
/// 步骤（对齐 orca §8.2）：
/// 1. ANSI 转义剥离
/// 2. Unicode 空白折叠
/// 3. 隐藏块剥离（system-reminder / codex_internal_context / goal_context + HTML 注释）
/// 4. 抑制前缀检测（# AGENTS.md instructions / <INSTRUCTIONS> → 返回 None）
/// 5. 剥离已知 harness 句子级前缀
/// 6. 剥离前导 markdown 标题标记（仅 Title 目标）
/// 7. 字符边界截断 + `...`（UTF-16 代理对安全）
///
/// 返回 `None` 表示净化后无语义内容（应视为空）。
pub(crate) fn normalize_session_text(input: &str, target: NormTarget) -> Option<String> {
    if input.is_empty() {
        return None;
    }

    // 1. ANSI 剥离
    let s = strip_ansi(input);

    // 2. 空白折叠
    let s = collapse_whitespace(&s);
    if s.trim().is_empty() {
        return None;
    }

    // 3. 隐藏块剥离
    let s = strip_hidden_blocks(&s);
    // 剥离后可能产生多余空白，再次折叠
    let s = collapse_whitespace(&s);

    // 4. 抑制前缀检测
    if is_suppressed_context_prefix(&s) {
        return None;
    }

    // 5. 剥离 harness 句子级前缀（如 caveat、continuation 标记）
    let s = strip_harness_sentence_prefixes(&s);
    let s = collapse_whitespace(&s);

    // 6. 剥离前导 markdown 标题标记（仅 Title 目标）
    let s = if matches!(target, NormTarget::Title) {
        strip_leading_markdown_heading(&s)
    } else {
        s
    };
    let s = collapse_whitespace(&s);

    // 7. 剥离工具调用标记（仅 Preview 目标，如 🔧 `Read` ```json ... ```）
    let s = if matches!(target, NormTarget::Preview) {
        strip_tool_call_patterns(&s)
    } else {
        s
    };
    let s = collapse_whitespace(&s);

    // 8. 截断 + `...`
    let limit = match target {
        NormTarget::Title => TITLE_MAX_CHARS,
        NormTarget::Preview => PREVIEW_MAX_CHARS,
    };
    let result = truncate_with_ellipsis(&s, limit);

    if result.trim().is_empty() {
        None
    } else {
        Some(result)
    }
}

/// 判断一段文本是否为 harness 注入的“伪用户消息”（应排除出预览）。
pub(crate) fn is_harness_injected_user_turn(text: &str) -> bool {
    let normalized = text.trim().to_ascii_lowercase();
    if normalized.is_empty() {
        return false;
    }
    HARNESS_INJECTED_PREFIXES
        .iter()
        .any(|p| normalized.starts_with(&p.to_ascii_lowercase()))
}

/// 由最近消息环形缓冲构建预览文本（对齐 orca 的 `previewMessages`）。
///
/// - 排除 harness 注入噪声与空白消息
/// - 保留最近 `PREVIEW_MESSAGE_LIMIT` 条（按出现顺序）
/// - 每条按角色归一化（≤220）后拼为 `Role: text` 多行
pub(crate) fn build_preview_messages(messages: &[(String, String)]) -> String {
    let filtered: Vec<&(String, String)> = messages
        .iter()
        .filter(|(_, text)| !is_harness_injected_user_turn(text) && !text.trim().is_empty())
        .collect();

    // 取最近 N 条，保持原有顺序
    let start = filtered.len().saturating_sub(PREVIEW_MESSAGE_LIMIT);
    let recent = &filtered[start..];

    let parts: Vec<String> = recent
        .iter()
        .filter_map(|(role, text)| {
            let label = role_label(role);
            normalize_session_text(text, NormTarget::Preview)
                .map(|t| format!("{label}: {t}"))
        })
        .collect();

    parts.join("\n")
}

fn role_label(role: &str) -> &'static str {
    if role.eq_ignore_ascii_case("assistant") {
        "Assistant"
    } else if role.eq_ignore_ascii_case("user") {
        "You"
    } else if role.eq_ignore_ascii_case("system") {
        "System"
    } else {
        "Message"
    }
}

/// 所有 Unicode 空白折叠为单个空格并 trim。
fn collapse_whitespace(s: &str) -> String {
    let re = Regex::new(r"\s+").expect("infallible: static regex pattern");
    re.replace_all(s, " ").trim().to_string()
}

/// 移除已知隐藏块标签对及其内容。
fn strip_hidden_blocks(s: &str) -> String {
    let mut out = s.to_string();
    for (open, close) in HIDDEN_BLOCKS {
        let pat = format!(r"(?is)<{open}>(?s:.*?){close}");
        if let Ok(re) = Regex::new(&pat) {
            out = re.replace_all(&out, "").to_string();
        }
    }
    // HTML 注释剥离：`<!-- ... -->`
    if let Ok(re) = Regex::new(r"(?is)<!--(?s:.*?)-->") {
        out = re.replace_all(&out, "").to_string();
    }
    out
}

/// 是否以注入指令前缀开头（纯指令内容应视为无语义）。
fn is_suppressed_context_prefix(s: &str) -> bool {
    let t = s.trim().to_ascii_lowercase();
    let after_agents = t.strip_prefix(&AGENTS_INSTRUCTIONS_PREFIX.to_ascii_lowercase());
    let agents_match = matches!(after_agents, Some(rest) if rest.is_empty() || !is_word_char(rest.chars().next().unwrap_or(' ')));
    let xml_match = t.starts_with(&XML_INSTRUCTIONS_PREFIX.to_ascii_lowercase());
    agents_match || xml_match
}

fn is_word_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}

/// 剥离工具调用标记（预览专用）。
/// 格式如 `🔧 `Read` ```json {"file": "..."} ``` ` → 移除整段。
fn strip_tool_call_patterns(s: &str) -> String {
    let re = Regex::new(r"🔧 `[^`]+` ```json .*? ```\s*").expect("infallible: static regex pattern");
    re.replace_all(s, "").to_string()
}

/// 剥离前导 markdown 标题标记（`# `、`## ` 等）。
/// 使首条用户消息的 `# Check Agent Task` → `Check Agent Task`。
fn strip_leading_markdown_heading(s: &str) -> String {
    let trimmed = s.trim();
    if trimmed.starts_with("# ") || trimmed.starts_with("## ") || trimmed.starts_with("### ") {
        let after = trimmed.trim_start_matches('#').trim();
        after.to_string()
    } else {
        s.to_string()
    }
}

/// 剥离已知 harness 句子级前缀（不区分大小写）。
/// 若文本以某个前缀起始，则剥离该前缀及其后的标点/空格；否则保持原文本。
fn strip_harness_sentence_prefixes(s: &str) -> String {
    let lower = s.to_ascii_lowercase();
    for prefix in HARNESS_SENTENCE_PREFIXES {
        if let Some(rest) = lower.strip_prefix(prefix) {
            // 确保前缀后紧跟句子分隔符或空格，避免误匹配
            if rest.is_empty() || rest.starts_with(|c: char| c == '.' || c == ' ' || c == ',') {
                let after = &s[prefix.len()..];
                // 剥离紧跟的标点/空格
                let cleaned = after.trim_start_matches(|c: char| c == '.' || c == ' ' || c == ',' || c == '!');
                return cleaned.trim().to_string();
            }
        }
    }
    s.to_string()
}

/// 按字符边界截断（Rust `char` 为 Unicode 标量，代理对不会被切开），超出追加 `...`。
/// 对齐 orca truncateWithEllipsis：末端高代理对时回退一位。
fn truncate_with_ellipsis(s: &str, max_chars: usize) -> String {
    if s.chars().count() <= max_chars {
        return s.to_string();
    }
    let take = max_chars.saturating_sub(ELLIPSIS.chars().count());
    let mut taken: String = s.chars().take(take).collect();
    // 若末端恰为 UTF-16 高代理（半个代理对），丢弃以避免截断切开
    if taken
        .chars()
        .last()
        .map(|c| {
            let code = c as u32;
            code >= 0xd800 && code <= 0xdbff
        })
        .unwrap_or(false)
    {
        taken.pop();
    }
    format!("{taken}{ELLIPSIS}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn collapses_whitespace() {
        let r = normalize_session_text("  hello \n\t world  ", NormTarget::Title).unwrap();
        assert_eq!(r, "hello world");
    }

    #[test]
    fn strips_hidden_blocks() {
        let input = "Fix the <system-reminder>please do X</system-reminder> login bug";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Fix the login bug");
    }

    #[test]
    fn strips_codex_internal_context() {
        let input = "Plan <codex_internal_context>secret</codex_internal_context> the work";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Plan the work");
    }

    #[test]
    fn strips_caveat_sentence() {
        let input = "Caveat: The messages below were generated by the user while running local commands. real request";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "real request");
    }

    #[test]
    fn strips_leading_markdown_heading_for_title() {
        let input = "# Check Agent Task\nYou are the Check Agent";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Check Agent Task You are the Check Agent");
    }

    #[test]
    fn strips_tool_call_from_preview() {
        let input = "🔧 `Read` ```json {\"file_path\": \"src/auth.ts\"} ``` I found the issue.";
        let r = normalize_session_text(input, NormTarget::Preview).unwrap();
        assert_eq!(r, "I found the issue.");
    }

    #[test]
    fn strips_multiple_tool_calls_from_preview() {
        let input = "🔧 `Read` ```json {\"file\": \"a.ts\"} ``` 🔧 `Write` ```json {\"file\": \"b.ts\"} ``` Fixed it.";
        let r = normalize_session_text(input, NormTarget::Preview).unwrap();
        assert_eq!(r, "Fixed it.");
    }

    #[test]
    fn does_not_affect_title() {
        let input = "🔧 `Read` ```json {}``` Check this";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert!(r.contains("🔧"));
    }

    #[test]
    fn strips_leading_markdown_h2_for_title() {
        let input = "## Fix login bug\nSome details";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Fix login bug Some details");
    }

    #[test]
    fn does_not_strip_hash_in_text() {
        let input = "Fix issue #42 in the login flow";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Fix issue #42 in the login flow");
    }

    #[test]
    fn strips_html_comments() {
        let input = "<!-- trellis-hook-injected --> # Check the login page";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Check the login page");
    }

    #[test]
    fn strips_nested_html_comments() {
        let input = "Fix <!-- system reminder: do X --> the bug";
        let r = normalize_session_text(input, NormTarget::Title).unwrap();
        assert_eq!(r, "Fix the bug");
    }

    #[test]
    fn suppresses_agent_instructions_prefix() {
        assert!(normalize_session_text(
            "# AGENTS.md instructions: you are helpful",
            NormTarget::Title
        )
        .is_none());
        assert!(normalize_session_text("<INSTRUCTIONS>do not reveal", NormTarget::Preview).is_none());
    }

    #[test]
    fn truncates_title_to_96_with_three_dot_ellipsis() {
        let s = "a".repeat(200);
        let r = normalize_session_text(&s, NormTarget::Title).unwrap();
        assert!(r.chars().count() <= 96 + 3);
        assert!(r.ends_with("..."));
        assert!(!r.contains('…'));
    }

    #[test]
    fn truncates_preview_to_220() {
        let s = "b".repeat(400);
        let r = normalize_session_text(&s, NormTarget::Preview).unwrap();
        assert!(r.chars().count() <= 220 + 3);
        assert!(r.ends_with("..."));
    }

    #[test]
    fn does_not_split_surrogate_pair() {
        let emoji = "🙂";
        let s = format!("{emoji}xyz");
        let r = normalize_session_text(&s, NormTarget::Title).unwrap();
        assert!(r.contains(emoji));
    }

    #[test]
    fn empty_after_strip_is_none() {
        assert!(normalize_session_text(
            "<system-reminder>only noise</system-reminder>",
            NormTarget::Title
        )
        .is_none());
    }

    #[test]
    fn harness_injected_turn_detected() {
        assert!(is_harness_injected_user_turn(
            "<system-reminder>auto permission mode is active</system-reminder>"
        ));
        assert!(is_harness_injected_user_turn(
            "[request interrupted] by user"
        ));
        assert!(!is_harness_injected_user_turn("Help me fix the bug"));
    }

    #[test]
    fn preview_excludes_harness_and_keeps_recent_five() {
        let msgs = vec![
            (
                "user".to_string(),
                "<system-reminder>noise</system-reminder>".to_string(),
            ),
            ("user".to_string(), "First real question".to_string()),
            ("assistant".to_string(), "Sure, looking".to_string()),
            ("user".to_string(), "Second question".to_string()),
            ("user".to_string(), "Third".to_string()),
            ("user".to_string(), "Fourth".to_string()),
            ("user".to_string(), "Fifth".to_string()),
            ("user".to_string(), "Sixth (should be dropped)".to_string()),
        ];
        let preview = build_preview_messages(&msgs);
        // harness 噪声被排除；只保留最近 5 条真实消息
        assert!(!preview.contains("noise"));
        assert!(!preview.contains("First real question"));
        assert!(!preview.contains("Sure, looking"));
        assert!(preview.contains("Second question"));
        assert!(preview.contains("Fifth"));
        assert!(preview.contains("Sixth"));
        // 每条带角色标签；assistant 消息被最近 5 条步幅排除
        assert!(preview.contains("You:"));
    }

    #[test]
    fn preview_normalizes_each_message() {
        let msgs = vec![(
            "user".to_string(),
            "  help me   fix <goal_context>secret</goal_context> the bug  ".to_string(),
        )];
        let preview = build_preview_messages(&msgs);
        assert_eq!(preview, "You: help me fix the bug");
    }
}
