import type { ProjectTabs } from '@/shared/types/tab';

/** Theme color map passed to the browser_start_picker Rust command. */
export interface PickerThemeColors {
  bgSecondary: string;
  bgTertiary: string;
  textPrimary: string;
  textMuted: string;
  borderColor: string;
  accentBlue: string;
}

/**
 * A single element picked in the browser.
 * `selector` is the shorthand selector generated by the injected picker
 * (e.g. `button#navCta`); multi-select payloads carry one entry per element.
 */
export interface PickerElement {
  /** The element's outerHTML. */
  html: string;
  /** Shorthand selector (tag + #id + first classes). */
  selector: string;
}

/**
 * Read the current application theme CSS variables from the root element.
 * Returns a color map that the PICKER_SCRIPT uses for styling.
 *
 * Falls back to dark-theme defaults when a variable is missing or empty
 * (e.g. in test environments where getComputedStyle returns blanks).
 */
export function getThemeColors(): PickerThemeColors {
  const style = getComputedStyle(document.documentElement);
  const v = (name: string, fallback: string): string =>
    style.getPropertyValue(name).trim() || fallback;
  return {
    bgSecondary: v('--bg-secondary', '#181A1C'),
    bgTertiary: v('--bg-tertiary', '#333337'),
    textPrimary: v('--text-primary', '#ffffff'),
    textMuted: v('--text-muted', '#999999'),
    borderColor: v('--border-color', '#3b3b40'),
    accentBlue: v('--accent-blue', '#2997ff'),
  };
}

/**
 * Check whether the given active tab is an Agent CLI terminal tab.
 * Pure function — no store access, fully testable.
 */
export function isAgentCliTab(
  projectTabs: ProjectTabs | undefined,
  activeTabId: string | null,
): boolean {
  if (!projectTabs || !activeTabId) return false;
  const tab = projectTabs.tabs.find((t) => t.id === activeTabId);
  if (!tab || tab.data.kind !== 'terminal') return false;
  return tab.data.agentId !== null;
}

/**
 * Format the message sent to the Agent CLI terminal when the user
 * picks one or more browser elements and enters a modification prompt.
 *
 * Single-element input keeps the singular header; multi-element input
 * numbers each element with its shorthand selector.
 *
 * Returns the full text including a trailing `\r` so the terminal
 * executes it immediately.
 */
export function formatPickerMessage(
  prompt: string,
  elements: PickerElement[],
  browserUrl: string,
): string {
  const plural = elements.length > 1;
  const lines: string[] = [
    `Please modify the following page element${plural ? 's' : ''}:`,
    '',
    `@${browserUrl}`,
    '',
    `Requirement: ${prompt}`,
    '',
  ];

  elements.forEach((element, i) => {
    if (plural) {
      lines.push(`Element ${i + 1} (${element.selector || 'unknown'}):`);
    } else {
      lines.push('Element HTML:');
    }
    lines.push('```html', element.html, '```');
    if (i < elements.length - 1) lines.push('');
  });

  return lines.join('\n');
}
